/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiStreamsRouteImport } from './routes/api/streams'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as ApiNetmirrorPreviewRouteImport } from './routes/api/netmirror.preview'
import { Route as ApiStreamsKeyRouteImport } from './routes/api/streams.$key'
import { Route as LiveCategoryStreamKeyRouteImport } from './routes/live.$category.$streamKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamsRoute = ApiStreamsRouteImport.update({
  id: '/api/streams',
  path: '/api/streams',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetmirrorPreviewRoute = ApiNetmirrorPreviewRouteImport.update({
  id: '/api/netmirror/preview',
  path: '/api/netmirror/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamsKeyRoute = ApiStreamsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiStreamsRoute,
} as any)
const LiveCategoryStreamKeyRoute = LiveCategoryStreamKeyRouteImport.update({
  id: '/live/$category/$streamKey',
  path: '/live/$category/$streamKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/recent': typeof RecentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/streams': typeof ApiStreamsRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/api/netmirror/preview': typeof ApiNetmirrorPreviewRoute
  '/api/streams/$key': typeof ApiStreamsKeyRoute
  '/live/$category/$streamKey': typeof LiveCategoryStreamKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/recent': typeof RecentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/streams': typeof ApiStreamsRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/api/netmirror/preview': typeof ApiNetmirrorPreviewRoute
  '/api/streams/$key': typeof ApiStreamsKeyRoute
  '/live/$category/$streamKey': typeof LiveCategoryStreamKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/movies': typeof MoviesRoute
  '/profile': typeof ProfileRoute
  '/recent': typeof RecentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/categories': typeof ApiCategoriesRoute
  '/api/chat': typeof ApiChatRoute
  '/api/streams': typeof ApiStreamsRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/api/netmirror/preview': typeof ApiNetmirrorPreviewRoute
  '/api/streams/$key': typeof ApiStreamsKeyRoute
  '/live/$category/$streamKey': typeof LiveCategoryStreamKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/favorites'
    | '/movies'
    | '/profile'
    | '/recent'
    | '/sitemap.xml'
    | '/api/categories'
    | '/api/chat'
    | '/api/streams'
    | '/category/$category'
    | '/api/netmirror/preview'
    | '/api/streams/$key'
    | '/live/$category/$streamKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/favorites'
    | '/movies'
    | '/profile'
    | '/recent'
    | '/sitemap.xml'
    | '/api/categories'
    | '/api/chat'
    | '/api/streams'
    | '/category/$category'
    | '/api/netmirror/preview'
    | '/api/streams/$key'
    | '/live/$category/$streamKey'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/favorites'
    | '/movies'
    | '/profile'
    | '/recent'
    | '/sitemap.xml'
    | '/api/categories'
    | '/api/chat'
    | '/api/streams'
    | '/category/$category'
    | '/api/netmirror/preview'
    | '/api/streams/$key'
    | '/live/$category/$streamKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  FavoritesRoute: typeof FavoritesRoute
  MoviesRoute: typeof MoviesRoute
  ProfileRoute: typeof ProfileRoute
  RecentRoute: typeof RecentRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiStreamsRoute: typeof ApiStreamsRouteWithChildren
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ApiNetmirrorPreviewRoute: typeof ApiNetmirrorPreviewRoute
  LiveCategoryStreamKeyRoute: typeof LiveCategoryStreamKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streams': {
      id: '/api/streams'
      path: '/api/streams'
      fullPath: '/api/streams'
      preLoaderRoute: typeof ApiStreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/netmirror/preview': {
      id: '/api/netmirror/preview'
      path: '/api/netmirror/preview'
      fullPath: '/api/netmirror/preview'
      preLoaderRoute: typeof ApiNetmirrorPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streams/$key': {
      id: '/api/streams/$key'
      path: '/$key'
      fullPath: '/api/streams/$key'
      preLoaderRoute: typeof ApiStreamsKeyRouteImport
      parentRoute: typeof ApiStreamsRoute
    }
    '/live/$category/$streamKey': {
      id: '/live/$category/$streamKey'
      path: '/live/$category/$streamKey'
      fullPath: '/live/$category/$streamKey'
      preLoaderRoute: typeof LiveCategoryStreamKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiStreamsRouteChildren {
  ApiStreamsKeyRoute: typeof ApiStreamsKeyRoute
}

const ApiStreamsRouteChildren: ApiStreamsRouteChildren = {
  ApiStreamsKeyRoute: ApiStreamsKeyRoute,
}

const ApiStreamsRouteWithChildren = ApiStreamsRoute._addFileChildren(
  ApiStreamsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  FavoritesRoute: FavoritesRoute,
  MoviesRoute: MoviesRoute,
  ProfileRoute: ProfileRoute,
  RecentRoute: RecentRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiChatRoute: ApiChatRoute,
  ApiStreamsRoute: ApiStreamsRouteWithChildren,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ApiNetmirrorPreviewRoute: ApiNetmirrorPreviewRoute,
  LiveCategoryStreamKeyRoute: LiveCategoryStreamKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
